CREATE TABLE BOOK
(
    TITLE     VARCHAR(100) NOT NULL,
    ISBM      VARCHAR(100) NOT NULL,
    AUTHOR    VARCHAR(100) NOT NULL,
    BOOK_TYPE VARCHAR(5)   NOT NULL
        CONSTRAINT BOOK_NOTE_DEFAULT DEFAULT '0',
    NOTE      VARCHAR(100) NULL
        CONSTRAINT BOOK_NOTE_DEFAULT DEFAULT 'DEFAULT',

    CONSTRAINT BOOK_PK PRIMARY KEY
        (
         TITLE,
         ISBM,
         AUTHOR
            )
)
