# 어플리케이션 내부에서 사용하는 프로젝트 정보를 정의합니다.
# 프로젝트 정보는 프로젝트의 모든 모듈에서 공유됩니다.
name: Spring-React_BaseProject_YourProjectNameHere
description: SpringBoot/React 템플릿 프로젝트입니다. 간단히 패키지명, 프로젝트명, 설명 등을 변경하고 사용하면 초기 개발 시간을 단축할 수 있습니다.
basePackage: org.spring.base
